# Configuration file for the Sphinx documentation builder.
#
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import subprocess
import sys
from pathlib import Path

from sphinx.application import Sphinx

# -- Project information -----------------------------------------------------

project = "Python による統計入門"
copyright = "2026, Nunu_3060"
author = "Nunu_3060"
release = "1.0"

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.mathjax",      # 数式を MathJax で表示する
    "sphinx.ext.githubpages",  # .nojekyll を出力する
]

language = "ja"
exclude_patterns: list[str] = []

# -- Options for HTML output -------------------------------------------------

html_theme = "sphinx_rtd_theme"
html_theme_options = {
    "navigation_depth": 3,
}
html_title = project

# 出力した HTML から rst ソースを閲覧できないようにする
html_show_sourcelink = False
html_copy_source = False

# 表のセル内で文字列を折り返すための CSS
html_static_path = ["_static"]
html_css_files = ["custom.css"]

# -- Figures generated by the sample code ------------------------------------

# 本文に載せるグラフを作成するサンプルコード
EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "examples"
IMAGES_DIR = Path(__file__).resolve().parent / "images"
FIGURE_SCRIPTS = [
    "ch04_visualization.py",
    "ch05_probability_distribution.py",
    "ch06_sampling_distribution.py",
    "ch10_correlation_regression.py",
]


def generate_figures(app: Sphinx) -> None:
    """サンプルコードを実行し、グラフの画像を source/images に出力する。

    Args:
        app: Sphinx アプリケーション
    """
    IMAGES_DIR.mkdir(exist_ok=True)
    for script in FIGURE_SCRIPTS:
        print(f"generating figures: {script}")
        subprocess.run(
            [sys.executable, str(EXAMPLES_DIR / script),
             "--outdir", str(IMAGES_DIR)],
            cwd=EXAMPLES_DIR, check=True, stdout=subprocess.DEVNULL)


def setup(app: Sphinx) -> None:
    """ビルドの開始時にグラフの画像を作成する。"""
    app.connect("builder-inited", generate_figures)
